name: 'conventional-gpt'
description: 'Github Action to use GPT to run code'
author: 'Nish Tahir'

branding:
  icon: 'code'
  color: 'green'

inputs:
  openai-api-key:
    description: 'OpenAI API Key'
    required: true
  github-token:
    description: 'Github Token'
    required: true
  model:
    description: 'Model to use for Review generation'
    required: false
    default: 'gpt-4o'
  conventions-file:
    description: 'Path to base code quality conventions'
    required: false
    default: '.github/CONVENTIONS.md'
  exclude-files:
    description: 'Files to exclude from review'
    required: false
    default: ''
runs:
  using: node20
  main: dist/index.js